# Generated by Django 3.2.6 on 2021-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('General query', 'GENERAL QUERY'), ('Where is my order', 'WHERE IS MY ORDER?'), ('Update my order', 'UPDATE MY ORDER'), ('Return or exchange of my order', 'RETURN OR EXCHANGE OF MY ORDER'), ('Complaint', 'COMPLAINT')], default='general_query', max_length=100),
        ),
    ]
