# Generated by Django 3.2.6 on 2021-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('general_query', 'GENERAL QUERY'), ('sign_in_or_sign_up_issue', 'SIGN IN OR SIGN UP ISSUE'), ('where_is_my_order', 'WHERE IS MY ORDER?'), ('update_my_order', 'UPDATE MY ORDER'), ('return_of_order', 'RETURN OF ORDER'), ('cancel_of_order', 'CANCEL OF ORDER'), ('complaint', 'COMPLAINT')], default='general_query', max_length=100),
        ),
    ]
